#!/bin/bash
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent
python busters.py -k 1 -l comp1 -p QLearningAgent

python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent
python busters.py -k 1 -l comp2 -p QLearningAgent

python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent
python busters.py -k 1 -l comp3 -p QLearningAgent

python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent
python busters.py -k 1 -l comp4 -p QLearningAgent

python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent
python busters.py -k 1 -l comp5 -p QLearningAgent

python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent
python busters.py -k 1 -l comp6 -p QLearningAgent

python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent
python busters.py -k 1 -l comp7 -p QLearningAgent

python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent
python busters.py -k 1 -l comp8 -p QLearningAgent

python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent
python busters.py -k 1 -l comp9 -p QLearningAgent

python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent
python busters.py -k 1 -l comp10 -p QLearningAgent

python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent
python busters.py -k 1 -l comp11 -p QLearningAgent

python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent
python busters.py -k 1 -l comp12 -p QLearningAgent


  python busters.py -k 1 -l contestClassic -p QLearningAgent
  python busters.py -k 2 -l contestClassic -p QLearningAgent
  python busters.py -k 3 -l contestClassic -p QLearningAgent
  python busters.py -k 4 -l contestClassic -p QLearningAgent
  python busters.py -k 1 -l mediumClassic -p QLearningAgent
  python busters.py -k 2 -l mediumClassic -p QLearningAgent
  python busters.py -k 3 -l mediumClassic -p QLearningAgent
  python busters.py -k 4 -l mediumClassic -p QLearningAgent
  python busters.py -k 1 -l minimaxClassic -p QLearningAgent
  python busters.py -k 2 -l minimaxClassic -p QLearningAgent
  python busters.py -k 3 -l minimaxClassic -p QLearningAgent
  python busters.py -k 4 -l minimaxClassic -p QLearningAgent
  python busters.py -k 4 -l trickyClassic -p QLearningAgent
  python busters.py -k 4 -l smallClassic -p QLearningAgent
  python busters.py -k 4 -l openHunt -p QLearningAgent
  python busters.py -k 4 -l openClassic -p QLearningAgent
